### ISSUE TITLE
Formatting Text in Shared Links for WhatsApp and Email

### ISSUE THREAD

**Issue by neerajydv23** [kudashevs/laravel-share-buttons#11]
In my Laravel app, I'm sharing URLs via WhatsApp and email, along with some details of the page (e.g., title, description, dates). However, the shared text appears in plain text, and I'm unable to add line breaks or format the labels using HTML. 

**Current Output**
When sharing the link, it appears as:
http://127.0.0.1:8000/projects/4/tasks/11 Task Title: task1, Description: This is the description, Assignee: Rahul, Assigned By: tester, Due Date: 2030-03-23

I would like the output to be formatted as follows:
http://127.0.0.1:8000/projects/4/tasks/11 
**Task Title:** task1, 
**Description:** This is the description, 
**Assignee:** Rahul, 
**Assigned By:** tester, 
**Due Date:** 2030-03-23

**Comment by kudashevs** [comment]
Could you please provide a screenshot of the current output?

**Comment by neerajydv23** [comment]
![Screenshot (28)](https://github.com/user-attachments/assets/2a65bdec-c27f-4722-a93e-b05a904a1922)
![Screenshot (29)](https://github.com/user-attachments/assets/29fb5e4d-9085-4531-ae8d-0ea57dc7f9a2)

**Comment by neerajydv23** [comment]
![Screenshot (30)](https://github.com/user-attachments/assets/36c0cbc2-20b1-4ed1-b2fd-98b3c2f488aa)
![Screenshot (31)](https://github.com/user-attachments/assets/52e7ec2f-8fd6-423a-8360-902e235f6204)

**Comment by kudashevs** [comment]
Let's separate the issue in two different tasks and go step-by-step.

First task: you want the output text to be formatted in WhatsApp while sharing.
Second task: you want the output text to be formatted when emailed to someone.

@neerajydv23 is that right?

**Comment by neerajydv23** [comment]
@kudashevs yes that's correct

**Comment by kudashevs** [comment]
To solve the current issue I need to update the app and implement the possibility to provide a text with different markups.
So, I created [another issue](https://github.com/kudashevs/laravel-share-buttons/issues/12), where I'll be experimenting with it. Once I'm done, I will let you know how to solve your issue.

**Comment by neerajydv23** [comment]
Thanks!

**Comment by kudashevs** [comment]
Hi @neerajydv23 

Back to your issue. I've implemented [the possibility to change the link text](https://github.com/kudashevs/laravel-share-buttons/issues/12) through the local options. Now, in [the new v5.2.0 release](https://github.com/kudashevs/laravel-share-buttons/releases/tag/v5.2.0), there is the possibility to provide a text with different markup directly to a method. So, let's go through your issue task by task. 

**First task:** you want the output text to be formatted in WhatsApp while sharing.

Now, you can provide a text with a markup to the whatsapp() method directly:
```
->whatsapp(['text' => '*Task Title:*' . "\n" . ' task1'])
```

**Second task**: you want the output text to be formatted when emailed to someone.

Now, you can provide html code to the email() method directly. But, this will work a little bit different from that you might expect. The problem is that you cannot put a raw HTML code in the href attribute of a link. So, to be shown correctly, the HTML code should be processed in a specific way (encoded). So, the code will be shown in an email, but it won't be interactive.

On the other hand, I implemented the possibility to access a page url (by default `:url` attribute in any text template) in the text.

I'll keep this issue open for a couple of days. Feel free to comment on the issue.

**Comment by neerajydv23** [comment]
okay i'll try it . thanks for the help!
